# Generated by Django 3.2.6 on 2022-09-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='dob',
            field=models.DateField(max_length=30, null=True),
        ),
    ]
