# Generated by Django 3.2.6 on 2022-11-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='multiple_subcategory_id',
        ),
    ]
