# Generated by Django 3.2.6 on 2022-08-28 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='cat',
            new_name='cat_id',
        ),
    ]
