# Generated by Django 3.2.6 on 2022-11-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='user_detail',
            name='sub_category',
            field=models.ManyToManyField(related_name='subcategory', to='core.SubCategory'),
        ),
    ]
