# Generated by Django 3.2.6 on 2022-08-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ImageField(max_length=250, upload_to='img')),
                ('name', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=200)),
            ],
        ),
    ]
