# Generated by Django 3.2.6 on 2022-09-16 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='created',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='created',
        ),
        migrations.RemoveField(
            model_name='country',
            name='created',
        ),
        migrations.RemoveField(
            model_name='states',
            name='created',
        ),
        migrations.RemoveField(
            model_name='testimonails',
            name='created',
        ),
        migrations.RemoveField(
            model_name='user_detail',
            name='created',
        ),
        migrations.RemoveField(
            model_name='user_gallery',
            name='created',
        ),
        migrations.RemoveField(
            model_name='website_gallery',
            name='created',
        ),
    ]
