# Generated by Django 3.2.6 on 2022-08-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('category', models.CharField(max_length=30)),
                ('sub_category', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('experiance', models.TextField()),
                ('bio', models.TextField()),
                ('discription', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
