# Generated by Django 3.2.6 on 2022-09-08 12:13

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=1, editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
