# Generated by Django 3.2.6 on 2022-10-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='tbl_states',
            name='country',
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='dob',
            field=models.DateField(max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='tbl_cities',
        ),
        migrations.DeleteModel(
            name='tbl_countries',
        ),
        migrations.DeleteModel(
            name='tbl_states',
        ),
    ]
