# Generated by Django 3.2.6 on 2022-08-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_cat_subcategory_cat_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='cat_id',
            new_name='cat',
        ),
    ]
