# Generated by Django 3.2.6 on 2022-11-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_detail_multiple_subcategory_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_detail',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='user_detail',
            name='sub_category',
            field=models.ManyToManyField(null=True, related_name='subcategory', to='core.SubCategory'),
        ),
    ]
