# Generated by Django 3.2.6 on 2022-09-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_detail_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='dob',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
