# Generated by Django 3.2.6 on 2022-09-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220918_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
