# Generated by Django 3.2.6 on 2022-09-04 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_detail_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_detail',
            old_name='user_id',
            new_name='user',
        ),
    ]
