# Generated by Django 3.2.6 on 2022-10-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20221002_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cities',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.states'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='sortname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='states',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='states',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='core.category'),
        ),
        migrations.AlterModelTable(
            name='cities',
            table='tbl_cities',
        ),
        migrations.AlterModelTable(
            name='country',
            table='tbl_countries',
        ),
        migrations.AlterModelTable(
            name='states',
            table='tbl_states',
        ),
    ]
