# Generated by Django 3.2.6 on 2022-09-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_website_profile_trusted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website_profile',
            name='trusted_by',
            field=models.FileField(upload_to='img'),
        ),
    ]
