# Generated by Django 3.2.6 on 2022-09-18 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220918_1617'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcribers',
            new_name='SubScribers',
        ),
    ]
