# Generated by Django 3.2.6 on 2022-08-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_img', models.ImageField(max_length=250, upload_to='img')),
                ('description', models.TextField()),
                ('member_name', models.CharField(max_length=50)),
                ('member_img', models.ImageField(max_length=250, upload_to='img')),
                ('member_skill', models.CharField(max_length=30)),
                ('fb_link', models.CharField(max_length=75)),
                ('twitter_link', models.CharField(max_length=75)),
                ('insta_link', models.CharField(max_length=75)),
                ('email_link', models.CharField(max_length=75)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=75)),
                ('mobile', models.IntegerField(unique=True)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='testimonails',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
