# Generated by Django 3.2.6 on 2022-08-28 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_detail_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
