# Generated by Django 3.2.6 on 2022-08-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220819_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='feature',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.IntegerField(default=1),
        ),
    ]
