# Generated by Django 3.2.6 on 2022-09-04 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220903_1525'),
        ('core', '0004_postimage'),
    ]

    operations = [
    ]
