# Generated by Django 3.2.6 on 2022-08-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='feature',
            field=models.IntegerField(default=1),
        ),
    ]
