# Generated by Django 3.2.6 on 2022-08-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_detail_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='experiance',
            field=models.CharField(max_length=30),
        ),
    ]
