# Generated by Django 3.2.6 on 2022-08-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_subcategory_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='cat_id',
        ),
    ]
