# Generated by Django 3.2.6 on 2022-09-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_detail_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='image',
            field=models.ImageField(default=1, upload_to='img'),
            preserve_default=False,
        ),
    ]
