# Generated by Django 3.2.6 on 2022-08-24 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_subcategory_cat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='cat_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
            preserve_default=False,
        ),
    ]
