# Generated by Django 3.2.6 on 2022-09-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_user_detail_charges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_detail',
            old_name='user_id',
            new_name='user',
        ),
    ]
