# Generated by Django 3.2.6 on 2022-08-28 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_user_detail_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
