# Generated by Django 3.2.6 on 2022-08-25 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_cat_id_subcategory_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='cat',
            field=models.IntegerField(),
        ),
    ]
